//
// Created by markus on 24.09.19.
//

#ifndef DEJAVU_CONFIGURATION_H
#define DEJAVU_CONFIGURATION_H

#define CONFIG_BACKTRACK false
#define CONFIG_THREADS 2

#define CONFIG_REFINEMENT_WORKERS  2
#define CONFIG_SIFT_PIPELINE_DEPTH 2

#endif //DEJAVU_CONFIGURATION_H
