//
// Created by markus on 24.09.19.
//

#ifndef DEJAVU_CONFIGURATION_H
#define DEJAVU_CONFIGURATION_H

#define CONFIG_IR_BACKTRACK true
#define CONFIG_IR_BACKTRACK_RANDOM true
#define CONFIG_IR_INVARIANT 0

#define CONFIG_THREADS_NO_PIPELINE 2
#define CONFIG_THREADS_REFINEMENT_WORKERS  2
#define CONFIG_THREADS_PIPELINE_DEPTH 2

#endif //DEJAVU_CONFIGURATION_H
